services:
  - type: web
    name: clinicalnlp-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    pythonVersion: 3.11.8
    plan: free